deployScripts:
  start:
    - npm install --unsafe-perm=true --allow-root
    - npm run compile
    - pm2 start ./pm2.json
  stop:
    - pm2 stop nideshop
  restart:
    - npm install --unsafe-perm=true --allow-root
    - npm run compile
    - pm2 restart nideshop